# Generated by Django 3.2 on 2021-05-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_postitem_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalpage',
            name='followed_by',
        ),
        migrations.AlterField(
            model_name='postitem',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='mainapp.personalpage'),
        ),
    ]
