# Generated by Django 3.2 on 2021-05-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_personalpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='blog',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mainapp.personalpage'),
            preserve_default=False,
        ),
    ]
