# Generated by Django 3.2 on 2021-05-02 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_viewedposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewedposts',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='viewedposts',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='viewedposts',
            unique_together={('user', 'post')},
        ),
    ]
