version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sanlobach
      POSTGRES_PASSWORD: personalblog789
      POSTGRES_DB: blogs
  backend:
    build:
      context: .
    volumes:
      - static_vol:/static
    expose:
      - 8080
    command: bash -c "
      ./wait-for-postgres.sh db
      && python manage.py migrate
      && python manage.py initadmin
      && gunicorn personal_blog.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_vol:/static
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  static_vol: